//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User1
    {
        public int id { get; set; }
        public string displayName { get; set; }
        public string userName { get; set; }
        public string pass_Word { get; set; }
        public Nullable<int> idRole { get; set; }
    
        public virtual UserRole UserRole { get; set; }
    }
}
