//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public string Color { get; set; }
        public string PublishYear { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string DrivingType { get; set; }
        public Nullable<int> Seats { get; set; }
        public string LicensePlate { get; set; }
        public Nullable<int> Price { get; set; }
        public string ImagePath { get; set; }
        public string TutorialPath { get; set; }
        public string City { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    }
}
