//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int id { get; set; }
        public Nullable<int> orderId { get; set; }
        public Nullable<int> userId { get; set; }
        public string status { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> paid { get; set; }
        public Nullable<int> remain { get; set; }
        public Nullable<int> receivedFee { get; set; }
        public string feedback { get; set; }
        public string returnCarStatus { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
    }
}
