//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ID { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Status { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Paid { get; set; }
        public Nullable<int> Remain { get; set; }
        public Nullable<int> ReceivedFee { get; set; }
        public string Feedback { get; set; }
        public string ReturnCarStatus { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    }
}
