//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int id { get; set; }
        public string phoneNumber { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string idCard { get; set; }
        public string address { get; set; }
        public string imageIdCardFront { get; set; }
        public string imageIdCardBack { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }

        public int ID { get { return id; } set { id = value; } }
        public string Name { get { return name; } set { name = value; } }
        public string PhoneNumber { get { return phoneNumber; } set { phoneNumber = value; } }

        public string Email { get { return email; } set { email = value; } }

        public string IdCard { get { return idCard; } set { idCard = value; } }

        public string Address { get { return address; } set { address = value; } }
        public string ImageIdCardFront { get { return imageIdCardFront; } set { imageIdCardFront = value; } }
        public string ImageIdCardBack { get { return imageIdCardBack; } set { imageIdCardBack = value; } }

        public Nullable<System.DateTime> CreatedAt { get { return createdAt; } set { createdAt = value; } }
        public Nullable<System.DateTime> UpdatedAt { get { return updatedAt; } set { updatedAt = value; } }
    }
}
